import "./globals.css";

import localFont from "next/font/local";
import LoadingGlobal from "./components/LoadingGlobal";
import Main from "./components/Main";
import Footer from "./components/Footer";
import { LocaleProvider } from "@/context/LocaleContext";
import { ThemeProvider } from "@/context/ThemeContext";
import { Suspense } from "react";
import loading from "./loading";

const kidsFont = localFont({
  src: "../../public/assets/fonts/opendyslexic/OpenDyslexic-Regular.woff2",
  display: "swap",
  variable: "--custom-font"
});

export const metadata = {
  title: "Learningdoes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <head>
        <script dangerouslySetInnerHTML={{
          __html: `
            (function(){
              const stored = localStorage.getItem("theme");
              const theme = stored || (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
              document.documentElement.classList.add(theme);
            })();
          `,
        }} />
      </head> */}
      <body className={`${kidsFont.className}`}>
        <ThemeProvider>
          {/* <LoadingGlobal /> */}
          <Suspense fallback={<loading />}>
            <LoadingGlobal>
              <LocaleProvider>
                <Main>
                  {children}
                </Main>
                <Footer nameApp="Learningdoes" />
              </LocaleProvider>
            </LoadingGlobal>
          </Suspense>
        </ThemeProvider>

      </body>
    </html>
  );
}
